Repository dkdlelk99/CSOS-Algorithm, pull requests merged in 2021-11, with the labels that each got.

#197 [1012 유기농 배추] 2차 시도 실패
  개팬다/dkdlelk99/1012/2차 시도 반례.md
  개팬다/dkdlelk99/1012/dkdlelk99_2.py
Labels: 안풀림, 도움 요청, Hard, Silver

#215 11/1 문제풀이
  개팬다/hojun/2580.py
Labels: 안풀림, Gold

#216 [1697 숨바꼭질] 리트 Fail
  개팬다/dkdlelk99/1697/dkdlelk99_2.py
Labels: 안풀림, Silver

#219 [1697 숨바꼭질] 굴복함
  BOJ/1697/README.md
  BOJ/1697/dkdlelk99.py
Labels: 풀이 완료, Silver

#224 [2108 통계학] 날먹하려다 실패 ㅎㅎ
  개팬다/dkdlelk99/2108/README.md
  개팬다/dkdlelk99/2108/dkdlelk99.py
Labels: 안풀림, Silver

#231 [2108 통계학] 최소한의 양심으로 풀이 다르게 함
  BOJ/2108/README.md
  BOJ/2108/dkdlelk99.py
Labels: 풀이 완료, Silver

#238 11/10 [15650 N과 M (2)] recursive function을 이용한 정석 풀이
  BOJ/15650/README.md
  BOJ/15650/dkdlelk99.py
  개팬다/dkdlelk99/2108/README.md
  개팬다/dkdlelk99/2108/dkdlelk99.py
Labels: 풀이 완료, Normal, Silver

#243 11/11 [15652 N과M (4)] 하나 풀어두니까 날먹 가능~~
  BOJ/15652/dkdlelk99.py
Labels: 풀이 완료, EZ, Silver
