Repository dkdlelk99/CSOS-Algorithm, pull requests merged in 2021-08, with the labels that each got.

#46 스택
  BOJ/10828/README.md
  BOJ/10828/dkdlelk99.py
Labels: EZ, Silver, 풀이 완료

#50 10866 덱
  BOJ/10866/README.md
  BOJ/10866/dkdlelk99.py
Labels: EZ, Silver, 풀이 완료

#52 10845 큐
  BOJ/10845/README.md
  BOJ/10845/dkdlelk99.py
Labels: EZ, Silver, 풀이 완료

#57 요세푸스 11866
  BOJ/11866/README.md
  BOJ/11866/dkdlelk99.py
Labels: Normal, Silver, 풀이 완료

#59 08.04 일자 문제풀이
  BOJ/10950/ghwns82.py
  BOJ/14681/ghwns82.py
  BOJ/2739/ghwns82.py
  BOJ/2884/ghwns82.py
  BOJ/8393/README.md
  BOJ/8393/ghwns82.py
Labels: 풀이 완료, Bronz

#61 수 찾기 1920 #자료구조를 잘 알아야 하는 이유
  BOJ/1920/README.md
  BOJ/1920/dkdlelk99.py
Labels: 리뷰 요청, 풀이 완료, Normal, Silver

#62 내일은 아침에 백준간다
  BOJ/1546/README.md
  BOJ/1546/hikang.py
  BOJ/3052/README.md
  BOJ/3052/hikang.py
Labels: 풀이 완료, EZ, Bronz

#70 [11723 집합] 오랜만에 PS
  BOJ/11723/README.md
  BOJ/11723/dkdlelk99.py
Labels: 풀이 완료, EZ, Silver

#74 [1620 나는야 포켓몬 마스터 이다솜]
  BOJ/1620/README.md
  BOJ/1620/dkdlelk99.py
Labels: 풀이 완료, EZ, Silver

#72 0809
  BOJ/15596/README.md
  BOJ/15596/hikang.py
  BOJ/4673/README.md
  BOJ/4673/hikang.py
Labels: 풀이 완료, EZ, Bronz

#78 [1764 듣보잡] set 문제
  BOJ/1764/README.md
  BOJ/1764/dkdlelk99.py
Labels: 풀이 완료, EZ, Silver

#79 오늘은 좀 재밋는 문제다!!
  BOJ/1475/README.md
  BOJ/1475/hikang.py
  BOJ/2018/README.md
  BOJ/2018/hikang.py
Labels: 풀이 완료, Silver

#82 [1463 1로 만들기] DP 문제 실패 ㅠㅠ
  개팬다/dkdlelk99/1463/README.md
  개팬다/dkdlelk99/1463/dkdlelk99.py
Labels: 안풀림, Hard, Silver

#86 [1463 1로 만들기] 리트 성공 DP
  BOJ/1463/README.md
  BOJ/1463/dkdlelk99.py
Labels: 풀이 완료, Hard, Silver

#87 ez
  BOJ/2941/README.md
  BOJ/2941/hikang.py
Labels: 풀이 완료, EZ, Silver

#90 08.19 일자 1065 한수(등비수열)이 재미있었음
  BOJ/1065/ghwns82.py
  BOJ/11654/ghwns82.py
  BOJ/11720/ghwns82.py
Labels: 풀이 완료, EZ, Bronz

#92 08.20 일자 코딩
  BOJ/10809/README.md
  BOJ/10809/ghwns82.py
  BOJ/1157/README.md
  BOJ/1157/ghwns82.py
  BOJ/2675/README.md
  BOJ/2675/ghwns82.py
Labels: 리뷰 요청, 풀이 완료, EZ, Bronz

#88 [9095 1, 2, 3 더하기] Brute force PS (DP ?)
  BOJ/9095/README.md
  BOJ/9095/dkdlelk99.py
Labels: 풀이 완료, Hard, Silver

#96 08.23 일자 코딩
  BOJ/1152/README.md
  BOJ/1152/ghwns82.py
  BOJ/2908/README.md
  BOJ/2908/ghwns82.py
Labels: EZ, Bronz

#97 [1003 피보나치 함수] DP(?)도 유형 익히니까 풀만하다
  BOJ/1003/README.md
  BOJ/1003/dkdlelk99.py
  BOJ/2630/README.md
Labels: 리뷰 요청, 풀이 완료, EZ, Silver

#103 [11726 2xn 타일링] ????????
  BOJ/11726/README.md
  BOJ/11726/dkdlelk99.py
  개팬다/dkdlelk99/11726/README.md
  개팬다/dkdlelk99/11726/dkdlelk99.py
Labels: 풀이 완료, 안풀림, Hard, Silver

#118 나이순 정렬
  BOJ/10814/README.md
  BOJ/10814/hikang.py
Labels: 풀이 완료, EZ, Silver

#116 [11724 연결 요소의 개수] 오늘도 그래프 문제
  BOJ/11724/README.md
  BOJ/11724/dkdlelk99.py
Labels: 풀이 완료, Normal, Silver
