Repository dkdlelk99/CSOS-Algorithm, pull requests merged in 2021-09, with the labels that each got.

#122 [11279 최대 힙]
  BOJ/11279/README.md
  BOJ/11279/dkdlelk99.py
Labels: 풀이 완료, EZ, Silver

#129 09.01 일자 소수 문제 두개
  BOJ/1978/ghwns82.py
  BOJ/2581/README.md
  BOJ/2581/ghwns82.py
Labels: Silver

#127 [18870 좌표 압축] sorting 문제
  BOJ/18870/README.md
  BOJ/18870/dkdlelk99.py
Labels: 풀이 완료, Normal, Silver

#132 단어 정렬
  BOJ/1181/README.md
  BOJ/1181/hikang.py
Labels: 풀이 완료, EZ, Silver

#135 [1927 최대 힙]
  BOJ/1927/README.md
  BOJ/1927/dkdlelk99.py
Labels: 풀이 완료, EZ, Silver

#143 09.06 코딩
  BOJ/1085/ghwns82.py
  BOJ/3009/README.md
  BOJ/3009/ghwns82.py
Labels: 풀이 완료, Bronz

#139 [1931 회의실 배정] 뿌ㅡㅡㅡㅡㅡ듯
  BOJ/1931/README.md
  BOJ/1931/dkdlelk99.py
Labels: 풀이 완료, Hard, Silver

#131 유기농 배추 폭사
  개팬다/dkdlelk99/1012/README.md
  개팬다/dkdlelk99/1012/dkdlelk99.py
Labels: 안풀림, 도움 요청, Hard, Silver

#148 좌표 정렬
  BOJ/11650/hikang.py
  BOJ/11866/hikang.py
Labels: 풀이 완료, EZ, Silver

#150 09.07 문제풀이
  BOJ/1002/README.md
  BOJ/1002/ghwns82.py
  BOJ/3053/README.md
  BOJ/3053/ghwns82.py
  BOJ/4153/ghwns82.py
Labels: Bronz, Silver

#152 [1676 팩토리얼 0의 개수] [17219 비밀번호 찾기] 최근에 어려운거에 너무 시달려서 쉬운거 두 개
  BOJ/1676/README.md
  BOJ/1676/dkdlelk99.py
  BOJ/17219/dkdlelk99.py
Labels: 풀이 완료, EZ, Normal, Silver

#156 09.08 문제풀이 --재귀
  BOJ/10870/README.md
  BOJ/10870/ghwns82.py
  BOJ/10872/README.md
  BOJ/10872/ghwns82.py
  BOJ/2447/README.md
  BOJ/2447/ghwns82.py
Labels: 풀이 완료, Bronz, Silver

#146 [1697 숨바꼭질] 너비 우선 탐색 DFS문제 실패
  개팬다/dkdlelk99/1697/README.md
  개팬다/dkdlelk99/1697/dkdlelk99.py
Labels: 안풀림, Hard, Silver

#157 [1260] DFS BFS 실패
  개팬다/dkdlelk99/1260/README.md
  개팬다/dkdlelk99/1260/dkdlelk99.py
Labels: 안풀림, Hard, Silver

#168 큐
  BOJ/10845/README.md
  BOJ/10845/hikang.py
Labels: 풀이 완료, EZ, Silver

#167 [이중 우선순위 큐]
  개팬다/dkdlelk99/7662/README.md
  개팬다/dkdlelk99/7662/dkdlelk99.py
Labels: 안풀림, Gold

#173 [Four Squares 17626] fail,.,.,.
  개팬다/dkdlelk99/17626/README.md
  개팬다/dkdlelk99/17626/dkdlelk99.py
Labels: 안풀림, Normal, Silver

#179 [DFS와 BFS] 2차 도전 실패함
  개팬다/dkdlelk99/1260/retry.py
Labels: Normal, Silver

#178 소수문제 시간 초과,,,
  BOJ/1929/README.md
  BOJ/1929/hikang.py
  개팬다/hikang/1929.py
Labels: 안풀림, Silver

#181 [11651 좌표 정렬하기 2] 즐거운 연휴~
  BOJ/11650/README.md
  BOJ/11651/README.md
  BOJ/11651/dkdlelk99.py
Labels: 풀이 완료, EZ, Silver

#187 [four squares 17626] dp인줄 알았냐
  개팬다/dkdlelk99/17626/answer.py
Labels: Hard, Silver

#189 [11653 소인수분해] 좋은 주말~~~~
  BOJ/11653/dkdlelk99.py
Labels: 풀이 완료, EZ, Silver

#190 괄호
  BOJ/9012/README.md
  개팬다/hikang/9012.py
Labels: 안풀림, Silver

#192 [Z 1074] 분할정복
  BOJ/1074/REDME.md
  BOJ/1074/dkdlelk99.py
Labels: 풀이 완료, Hard, Silver

#194 괄호 문제 완료
  BOJ/9012/hikang.py
Labels: 풀이 완료, Silver

#202 [DFS와 BFS 1260] 리트라이 성공~!
  BOJ/1260/README.md
  BOJ/1260/dkdlelk99.py
  개팬다/dkdlelk99/1260/dkdlelk99_last_ver.py
Labels: 풀이 완료, Normal, Silver
