Repository dkdlelk99/CSOS-Algorithm, pull requests merged in 2021-07, with the labels that each got.

#20 2292 벌집 (품)/2231 분해합 (2트 실패)
  BOJ/1000/README.md
  BOJ/1001/README.md
  BOJ/1008/README.md
  BOJ/10171/README.md
  BOJ/10172/README.md
  BOJ/10718/README.md
  BOJ/1085/README.md
  BOJ/10998/README.md
  BOJ/2231/README.md
  BOJ/2231/dkdlelk99.py
  BOJ/2292/README.md
  BOJ/2292/dkdlelk99.py
  BOJ/2557/README.md
  BOJ/4153/README.md
  개팬다/dkdlelk99/2231/dkdlelk99.py
  개팬다/dkdlelk99/2231/풀이.md
  개팬다/dkdlelk99/README.md
Labels: 도움 요청, 안풀림, 풀이 완료

#30 나이순 정렬, 체스판 다시 칠하기
  BOJ/1018/README.md
  BOJ/1018/dkdlelk99.py
  BOJ/10814/README.md
  BOJ/10814/dkdlelk99.py
Labels: Silver, 풀이 완료

#32 괄호(오늘부터 한 문제씩~)
  BOJ/9012/README.md
  BOJ/9012/dkdlelk99.py
Labels: Normal, Silver, 풀이 완료

#38 2164 카드 2
  개팬다/dkdlelk99/2164/README.md
  개팬다/dkdlelk99/2164/dkdlelk99.py
Labels: Hard, Silver, 도움 요청, 안풀림

#35 10718번 풀음
  BOJ/10718/ghwns82.py
  BOJ/2557/ghwns82.py
Labels: Bronz, EZ, 풀이 완료

#34 꿀
  BOJ/15552/README.md
  BOJ/15552/hikang.py
  BOJ/2741/README.md
  BOJ/2741/hikang.py
  BOJ/2742/README.md
  BOJ/2742/hikang.py
  BOJ/8393/README.md
  BOJ/8393/hikang.py
Labels: Bronz, EZ, 풀이 완료

#42 소수 찾기
  BOJ/1978/README.md
  BOJ/1978/dkdlelk99.py
Labels: Normal, Silver, 풀이 완료
