Repository dkdlelk99/CSOS-Algorithm, pull requests merged in 2022-02, with the labels that each got.

#248 11/12 [15645 N과 M (5)] 또 조합 문제
  BOJ/15654/dkdlelk99.py
Labels: 풀이 완료, Silver

#251 11/15 [15657 N과 M (8)] 백트레킹, 재귀에 대한 이해
  BOJ/15657/dkdlelk99.py
Labels: 풀이 완료, Silver

#262 0208, [10989] 2일차는 날먹
  BOJ/10989/dkdlelk99.py
Labels: 풀이 완료, Silver

#261 02.08 - 1085
  BOJ/1085/dbql99.py
  BOJ/4153/dbql99.py
Labels: 풀이 완료, EZ, Bronz

#267 2/9 두문제 완료
  BOJ/10250/JungJeeheun.c
  BOJ/15829/JungJeeheun.c
Labels: 풀이 완료, EZ, Bronz

#258 [1316] 그룹 단어 체커 fail (0207)
  개팬다/dkdlelk99/1316/README.md
  개팬다/dkdlelk99/1316/dkdlelk99.py
Labels: Normal, Silver

#265 [1427] 0209 소트인사이드
  BOJ/1427/dkdlelk99.py
Labels: 풀이 완료, EZ, Silver

#273 2/11 - 2231
  개팬다/dbql99/2231
Labels: 안풀림, Bronz

#272 [1934] 0211 최소공배수
  BOJ/1934/dkdlelk99.py
Labels: 풀이 완료, EZ, Silver

#276 2.14 / 2231
  BOJ/2231/dbql99.py
Labels: 리뷰 요청, 풀이 완료, Hard, Bronz

#278 [1181] 0214
  BOJ/1181/JungJeeheun.c(못품)
Labels: 안풀림

#277 [1316] 0214 그룹 단어 체커 복수 성공
  BOJ/1316/dkdlelkpp.py
Labels: 풀이 완료, Normal, Silver

#281 02-15/2292
  개팬다/dbql99/2292.py
Labels: 안풀림, 도움 요청, Hard, Bronz

#280 [2941] 0215 크로아티아 알파벳
  BOJ/2941/dkdlelk99.py
Labels: 풀이 완료, EZ, Silver

#288 2/16 문제 안풀림;
  개팬다/JungJeeheun/10814.c
Labels: 안풀림

#291 2/17 10814
  BOJ/10814/JungJeeheun.c
Labels: Silver

#284 [2581] 0216 소수
  BOJ/2581/dkdlelk99.py
Labels: 풀이 완료, EZ, Silver

#300 2/23 2164
  BOJ/2164/JungJeeheun.c
Labels: 풀이 완료, Silver

#299 2/23 문제풀이 - 1541번
  BOJ/1541/ghwns82.py
Labels: Silver

#289 [1158] 0217 요세푸스 문제 시간 초과
  BOJ/1158/README.md
  BOJ/1158/dkdlelk99.py
  개팬다/dkdlelk99/1158/README.md
  개팬다/dkdlelk99/1158/dkdlelk99.py
Labels: 안풀림, Silver

#301 2/24 9012번 실4
  BOJ/9012/JungJeeheun.c
Labels: 풀이 완료, Silver
